spring:
  main:
    banner-mode: OFF
  webflux:
    problemdetails:
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,mappings"
    jmx:
      exposure:
        include: "beans,health,mappings"
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    mappings:
      enabled: true

graphql:
  packages:
    - 'com.example.application.controller.graphql'
